Merging with upstream

diff --git a/.ci/templates/tests/templates/job-uhd-x4xx-hardware-tests.yml b/.ci/templates/tests/templates/job-uhd-x4xx-hardware-tests.yml
--- a/.ci/templates/tests/templates/job-uhd-x4xx-hardware-tests.yml
+++ b/.ci/templates/tests/templates/job-uhd-x4xx-hardware-tests.yml
@@ -18,6 +18,9 @@ parameters:
 - name: runRfnocBlockTest
   type: boolean
   default: false
+- name: forceIQCorrections
+  type: boolean
+  default: false
 - name: master_clock_rate
   type: string
   default: ''
@@ -36,8 +39,6 @@ parameters:
   values:
     - 'Filesystem'
     - 'Pipeline'
-- name: xilinxLocation
-  type: string
 - name: extra_rf_test_args
   type: string
   default: ''
@@ -55,8 +56,6 @@ jobs:
 - job: x4xx_hardware_test_${{ parameters.suiteName }}
   displayName: x4xx hardware test ${{ parameters.suiteName }}
   timeoutInMinutes: ${{ parameters.timeoutInMinutes }}
-  variables:
-    testOS: ''
   strategy:
     matrix: ${{ parameters.dutMatrix }}
 
@@ -71,15 +70,6 @@ jobs:
     clean: True
   - checkout: ettus-rts
     clean: True
-
-  - script: |
-      LSB_ID=$(lsb_release -i -s) # e.g. "Ubuntu"
-      LSB_RELEASE=$(lsb_release -r -s | tr -d .) # e.g. "2404"
-      # ${LSB_ID,,} is $LSB_ID in lower case
-      testOS=${LSB_ID,,}$LSB_RELEASE # e.g. "ubuntu2404"
-      echo '##vso[task.setvariable variable=testOS]'$testOS
-      echo testOS=$testOS
-    displayName: set testOS variable
 
   - script: |
       if [ "${{ parameters.uhdArtifactSource }}" = "current" ]; then
@@ -162,7 +152,6 @@ jobs:
     displayName: Create usrp_emb venv
 
   - script: |
-      source ${{ parameters.xilinxLocation }}/settings64.sh
       source $USRP_EMB_VENV/bin/activate
       usrp_emb_x4xx_flash_emmc
     displayName: Flash eMMC
@@ -200,10 +189,18 @@ jobs:
         scp -o StrictHostKeyChecking=no $(uhd_fpga_artifact_directory)/*/usrp_$(pytestDUT)_* root@$USRP_EMB_TARGET_IP:/usr/share/uhd/images/
         ssh -o StrictHostKeyChecking=no -tt root@$USRP_EMB_TARGET_IP "md5sum /usr/share/uhd/images/usrp_$(pytestDUT)_fpga_$(dutFPGA).bit > /usr/share/uhd/images/usrp_$(pytestDUT)_fpga_$(dutFPGA).bit.md5"
         ssh -o StrictHostKeyChecking=no -tt root@$USRP_EMB_TARGET_IP "md5sum /usr/share/uhd/images/usrp_$(pytestDUT)_fpga_$(dutFPGA).dts > /usr/share/uhd/images/usrp_$(pytestDUT)_fpga_$(dutFPGA).dts.md5"
-        ssh -o StrictHostKeyChecking=no -tt root@$USRP_EMB_TARGET_IP "rm /lib/firmware/x4*.* && systemctl restart usrp-hwd.service"
+        ssh -o StrictHostKeyChecking=no -tt root@$USRP_EMB_TARGET_IP "rm /lib/firmware/x4*.* && systemctl stop usrp-hwd.service"
+        ssh -o StrictHostKeyChecking=no -tt root@$USRP_EMB_TARGET_IP "umount /mnt/db*_flash || true && systemctl start usrp-hwd.service"
     displayName: Copy FPGA pipeline images to device
     condition: and(succeeded(), eq('${{ parameters.fpga_imgs_source }}', 'Pipeline'))
 
+  # This removes all binaries in /lib/firmware/ to avoid mpm failing to start
+  # because the fpga in there is too old (from the last uhd release) 
+  # It then restarts mpm (here the logs would give out errors about no fpga)
+  # Then flashes the latest pipeline-built bitfile already copied over
+  # Then stops mpm and deletes all the journalctl logs once to ignore
+  # all errors in there and then starts mpm again
+  # finally prints out information to confirm which fpga is flashed
   - script: |
         set -e
         ssh-keygen -f ~/.ssh/known_hosts -R $USRP_EMB_TARGET_IP
@@ -289,10 +286,10 @@ jobs:
       fi
       mkdir -p $(Common.TestResultsDirectory)/devtest
       cd $(Common.TestResultsDirectory)/devtest
-      if [ -z "$(master_clock_rate)" ]; then
+      if [ -z "${{ parameters.master_clock_rate }}" ]; then
         args="addr=$(sfp0ip),type=$(dutType)"
       else
-        args="addr=$(sfp0ip),type=$(dutType),master_clock_rate=$(master_clock_rate)"
+        args="addr=$(sfp0ip),type=$(dutType),master_clock_rate=${{ parameters.master_clock_rate }}"
       fi
       echo $args
       uhd_usrp_probe --args $args
@@ -325,63 +322,70 @@ jobs:
     displayName: cat devtest log
     condition: and(succeeded(), ${{ parameters.runDevTest }})
 
-  # warmUpAfterBoot optional parameter added to allow device to warm up before running tests
-  # For example, the phase test pass/fail requirements are based on declared specs measured after a warm up to 23 deg C
-  # https://www.ni.com/docs/en-US/bundle/ettus-usrp-x440-specs/page/specs.html#d668e1387
   - script: |
-      dig -x $(sfp0ip) +short
-      dig -x $USRP_EMB_TARGET_IP +short
+      # Set UHD installation path
       export UHD_INSTALL_PATH=$(uhd_artifact_directory)/uhddev-$(testOS)-${{ parameters.toolset }}/uhddev/build-installed
-      export GNURADIO_GRETTUS_INSTALL_PATH=$(uhd_artifact_directory)/gnuradio-grettus-$(testOS)-${{ parameters.toolset }}/gnuradio/build-installed
-      export PATH=$UHD_INSTALL_PATH/bin:$PATH
-      export PATH=$GNURADIO_GRETTUS_INSTALL_PATH/bin:$PATH
+      export CAL_DIR="$HOME/.local/share/uhd/cal"
       export PYTHON_VERSION=$(python3 -c "import sys; print('python' + str(sys.version_info.major) + '.' + str(sys.version_info.minor))")
-
+      
+      # Setup UHD environment
+      export PATH=$UHD_INSTALL_PATH/bin:$PATH
       if [ -d "$UHD_INSTALL_PATH/lib64" ]; then
-        export PATH=$UHD_INSTALL_PATH/lib64/uhd/examples:$PATH
         export LD_LIBRARY_PATH=$UHD_INSTALL_PATH/lib64:$LD_LIBRARY_PATH
-        export LD_LIBRARY_PATH=$GNURADIO_GRETTUS_INSTALL_PATH/lib64:$LD_LIBRARY_PATH
         export PYTHONPATH=$UHD_INSTALL_PATH/lib64/$PYTHON_VERSION/site-packages:$PYTHONPATH
-        export PYTHONPATH=$GNURADIO_GRETTUS_INSTALL_PATH/lib64/python3/dist-packages:$PYTHONPATH
+        UHD_UTILS_DIR="$UHD_INSTALL_PATH/lib64/$PYTHON_VERSION/site-packages/uhd/utils"
       else
-        export PATH=$UHD_INSTALL_PATH/lib/uhd/examples:$PATH
         export LD_LIBRARY_PATH=$UHD_INSTALL_PATH/lib:$LD_LIBRARY_PATH
-        export LD_LIBRARY_PATH=$GNURADIO_GRETTUS_INSTALL_PATH/lib:$LD_LIBRARY_PATH
         export PYTHONPATH=$UHD_INSTALL_PATH/lib/$PYTHON_VERSION/site-packages:$PYTHONPATH
-        export PYTHONPATH=$GNURADIO_GRETTUS_INSTALL_PATH/lib/python3/dist-packages:$PYTHONPATH
+        UHD_UTILS_DIR="$UHD_INSTALL_PATH/lib/$PYTHON_VERSION/site-packages/uhd/utils"
       fi
-      if [ ${{ parameters.warmUpAfterBoot }} > 0 ]; then
-        echo 'sleeping ${{ parameters.warmUpAfterBoot }} seconds before testing...'
-        sleep ${{ parameters.warmUpAfterBoot }}
-      fi
-      uhd_find_devices --args type=$(dutType)
-      uhd_usrp_probe --args addr=$USRP_EMB_TARGET_IP,type=$(dutType)
+      
+      # Activate virtual environment and install dependencies
+      source $USRP_EMB_VENV/bin/activate
+      pip3 install -r $(Build.SourcesDirectory)/ettus-rts/.ci/utils/x420_iq_dc_correction_requirements.txt
+      
+      # Run the X420 IQ correction script
+      python3 $(Build.SourcesDirectory)/ettus-rts/.ci/utils/x420_iq_dc_correction.py \
+        --device-ip $(sfp0ip) \
+        --mgmt-ip $USRP_EMB_TARGET_IP \
+        --uhd-utils-dir "$UHD_UTILS_DIR" \
+        --cal-dir "$CAL_DIR" \
+        --test-results-dir "$(Common.TestResultsDirectory)" \
+        --force-run-iq-corrections ${{ parameters.forceIQCorrections }}
+      
+      echo "X420 IQ correction completed"
+    displayName: Run IQ correction on $(pytestDUT)
+    condition: and(succeeded(), ${{ parameters.runPyTest }}, eq(variables['pytestDUT'], 'x420'))
 
-      # setup venv for pytest
-      source $(Build.SourcesDirectory)/ettus-rts/config/remote/python_tests/setup_venv.sh
+  - template: step-uhd-run-pytest-on-host.yml
+    parameters:
+      runPyTest: ${{ parameters.runPyTest }}
+      displayString: 'RF pytest'
+      testFolder: 'pytests'
+      testLength: ${{ parameters.testLength }}
+      extra_rf_test_args: ${{ parameters.extra_rf_test_args }}
+      warmUpAfterBoot: ${{ parameters.warmUpAfterBoot }}
+      toolset: ${{ parameters.toolset }}
 
-      # to split between tests requiring additional RF hardware or not we use different test directories
-      echo runPyTest: ${{ parameters.runPyTest }}
-      echo runPyTestNonRF: ${{ parameters.runPyTestNonRF }}
-      if [[ "${{ parameters.runPyTest }}" == "True" ]]; then
-        cd $(Build.SourcesDirectory)/ettus-rts/config/remote/python_tests/pytests
-        python3 ../automated_main.py --ats_config $(pytestAtsConfig) --dut $(pytestDUT) --run_vars_overrides 'mgmt_addr=$(USRP_EMB_TARGET_IP)' --results_path '$(Common.TestResultsDirectory)/pytest/host' --test_length ${{ parameters.testLength }} ${{ parameters.extra_rf_test_args }}
-      fi
-      if [[ "${{ parameters.runPyTestNonRF }}" == "True" ]]; then
-        cd $(Build.SourcesDirectory)/ettus-rts/config/remote/python_tests/pytests_non_rf
-        python3 ../automated_main.py --test_selector . --ats_config $(pytestAtsConfig) --dut $(pytestDUT) --run_vars_overrides 'mgmt_addr=$(USRP_EMB_TARGET_IP)' --results_path '$(Common.TestResultsDirectory)/pytest/host' --test_length ${{ parameters.testLength }} ${{ parameters.extra_rf_test_args }}
-      fi
-    displayName: Run pytest on host
-    continueOnError: true
-    condition: and(succeeded(), or(${{ parameters.runPyTest }}, ${{ parameters.runPyTestNonRF }}))
+  - template: step-uhd-run-pytest-on-host.yml
+    parameters:
+      runPyTest: ${{ parameters.runPyTestNonRF }}
+      displayString: 'Non-RF pytest'
+      testFolder: 'pytests_non_rf'
+      testLength: ${{ parameters.testLength }}
+      extra_rf_test_args: ${{ parameters.extra_rf_test_args }}
+      warmUpAfterBoot: ${{ parameters.warmUpAfterBoot }}
+      toolset: ${{ parameters.toolset }}
 
+  # TODO: remove version pinning once pytest is working again with higher versions
+  # TODO: use requirements.txt to install pytest dependencies
   - script: |
       dig -x $(sfp0ip) +short
       dig -x $USRP_EMB_TARGET_IP +short
       mkdir -p $(Common.TestResultsDirectory)/pytest/embedded
       cd $(Common.TestResultsDirectory)/pytest/embedded
       ssh-keygen -f ~/.ssh/known_hosts -R $USRP_EMB_TARGET_IP
-      ssh -o StrictHostKeyChecking=no -tt root@$USRP_EMB_TARGET_IP "pip3 install --upgrade pytest pytest-helpers-namespace pytest-tempdir pytest-salt"
+      ssh -o StrictHostKeyChecking=no -tt root@$USRP_EMB_TARGET_IP "pip3 install --upgrade 'pytest<8.4.0' pytest-helpers-namespace pytest-tempdir pytest-salt"
       ssh -o StrictHostKeyChecking=no -tt root@$USRP_EMB_TARGET_IP "rm -rf ~/usrp_pytest && mkdir -p ~/usrp_pytest"
       scp -o StrictHostKeyChecking=no -r $(Build.SourcesDirectory)/ettus-rts/config/remote/ root@$USRP_EMB_TARGET_IP:~/usrp_pytest
       ssh -o StrictHostKeyChecking=no -tt root@$USRP_EMB_TARGET_IP "cd ~/usrp_pytest/remote/python_tests/pytests && \
@@ -392,6 +396,15 @@ jobs:
     displayName: Run pytest on embedded
     continueOnError: true
     condition: and(succeeded(), ${{ parameters.runPyTest }})
+
+  - ${{ if parameters.runRfnocBlockTest }}:
+    - template: ../../steps-rfnoc-block-test.yml
+      parameters:
+        dutType: $(pytestDUT)
+        uhdInstallPath: $(uhd_artifact_directory)/uhddev-$(testOS)-${{ parameters.toolset }}/uhddev/build-installed
+        uhdFpgaArtifactSource: ${{ parameters.uhdFpgaArtifactSource }}
+        fpga_imgs_source: ${{ parameters.fpga_imgs_source }}
+        uhdArgs: type=$(dutType),addr=$(USRP_EMB_TARGET_IP)
 
   # Run the mender tests last because they
   # modify the flashed image on the device
@@ -461,14 +474,6 @@ jobs:
     artifact: test-logs-x4xx-hardware-$(dutName)-run$(System.JobAttempt)
     displayName: Upload Test Logs
     condition: always()
-
-  - ${{ if parameters.runRfnocBlockTest }}:
-    - template: ../../steps-rfnoc-block-test.yml
-      parameters:
-        dutType: $(pytestDUT)
-        uhdInstallPath: $(uhd_artifact_directory)/uhddev-$(testOS)-${{ parameters.toolset }}/uhddev/build-installed
-        uhdFpgaArtifactSource: ${{ parameters.uhdFpgaArtifactSource }}
-        fpga_imgs_source: ${{ parameters.fpga_imgs_source }}
 
   - script: |
       echo "A previous step failed. See steps with warnings."
